exports.seed = async function (knex) {
  await knex("Room").del();
  await knex("Room").insert([
    {RoomTypeID: 1, RoomNumber: "101", Status: "Available" },
    {RoomTypeID: 1, RoomNumber: "102", Status: "Available" },
    {RoomTypeID: 1, RoomNumber: "103", Status: "Available" },
    {RoomTypeID: 1, RoomNumber: "104", Status: "Available" },
    {RoomTypeID: 1, RoomNumber: "105", Status: "Available" },
    {RoomTypeID: 1, RoomNumber: "106", Status: "Available" },
    {RoomTypeID: 2, RoomNumber: "201", Status: "Booked" },
    {RoomTypeID: 2, RoomNumber: "202", Status: "Maintenance" },
    {RoomTypeID: 2, RoomNumber: "203", Status: "Available" },
    {RoomTypeID: 2, RoomNumber: "204", Status: "Available" },
    {RoomTypeID: 2, RoomNumber: "205", Status: "Available" },
    {RoomTypeID: 2, RoomNumber: "206", Status: "Available" },
    {RoomTypeID: 3, RoomNumber: "301", Status: "Available" },
    {RoomTypeID: 3, RoomNumber: "302", Status: "Booked" },
    {RoomTypeID: 3, RoomNumber: "303", Status: "Available" },
    {RoomTypeID: 3, RoomNumber: "304", Status: "Available" },
    {RoomTypeID: 3, RoomNumber: "305", Status: "Available" },
    {RoomTypeID: 3, RoomNumber: "306", Status: "Available" },
    {RoomTypeID: 4, RoomNumber: "401", Status: "Available" },
    {RoomTypeID: 4, RoomNumber: "402", Status: "Maintenance" },
    {RoomTypeID: 4, RoomNumber: "403", Status: "Available" },
    {RoomTypeID: 4, RoomNumber: "404", Status: "Available" },
    {RoomTypeID: 4, RoomNumber: "405", Status: "Available" },
    {RoomTypeID: 4, RoomNumber: "406", Status: "Available" },
    {RoomTypeID: 5, RoomNumber: "501", Status: "Available" },
    {RoomTypeID: 5, RoomNumber: "502", Status: "Booked" },
    {RoomTypeID: 5, RoomNumber: "503", Status: "Available" },
    {RoomTypeID: 5, RoomNumber: "504", Status: "Available" },
    {RoomTypeID: 5, RoomNumber: "505", Status: "Available" },
    {RoomTypeID: 5, RoomNumber: "506", Status: "Available" },
    {RoomTypeID: 6, RoomNumber: "601", Status: "Available" },
    {RoomTypeID: 6, RoomNumber: "602", Status: "Booked" },
    {RoomTypeID: 6, RoomNumber: "603", Status: "Available" },
    {RoomTypeID: 6, RoomNumber: "604", Status: "Available" },
    {RoomTypeID: 6, RoomNumber: "605", Status: "Available" },
    {RoomTypeID: 6, RoomNumber: "606", Status: "Available" },
  ]);
};
